Template repository changes: remal-github-actions/template-typescript

diff --git a/.github/actions/install-dependencies/action.yml b/.github/actions/install-dependencies/action.yml
--- a/.github/actions/install-dependencies/action.yml
+++ b/.github/actions/install-dependencies/action.yml
@@ -36,12 +36,22 @@ runs:
     id: cache-params
     shell: bash
     env:
-      CACHE_KEY: ${{runner.os}}-dependencies-${{inputs.nodeVersion}}-${{hashFiles('package.json', 'pnpm-*.yml', '.yarnrc.yml', 'yarn.lock' , '.pnp.*', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
+      CACHE_KEY_PREFIX: ${{runner.os}}-dependencies-${{inputs.nodeVersion}}-${{steps.package-manager.outputs.result}}-
+      CACHE_KEY_HASH: ${{hashFiles('package.json', 'pnpm-*.yml', '.yarnrc.yml', 'yarn.lock' , '.pnp.*', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
     run: |
-      echo "key=$CACHE_KEY" | tee -a "$GITHUB_OUTPUT"
+      if [ "$PACKAGE_MANAGER" == "pnpm" ]; then
+        PACKAGE_MANAGER_CACHE_DIR=$( pnpm store path )
+      elif [ "$PACKAGE_MANAGER" == "yarn" ]; then
+        PACKAGE_MANAGER_CACHE_DIR=$( yarn config get cacheFolder )
+      else
+        echo "::error::Unsupported package manager: $PACKAGE_MANAGER"
+        exit 1
+      fi
+      echo "key-prefix=$CACHE_KEY_PREFIX" | tee -a "$GITHUB_OUTPUT"
+      echo "key=${CACHE_KEY_PREFIX}${CACHE_KEY_HASH}" | tee -a "$GITHUB_OUTPUT"
       echo "paths<<EOF" | tee -a "$GITHUB_OUTPUT"
       echo "node_modules" | tee -a "$GITHUB_OUTPUT"
-      echo ".yarn/cache" | tee -a "$GITHUB_OUTPUT"
+      echo "$PACKAGE_MANAGER_CACHE_DIR" | tee -a "$GITHUB_OUTPUT"
       echo "EOF" | tee -a "$GITHUB_OUTPUT"
 
   - name: Restore dependencies cache
@@ -49,7 +59,7 @@ runs:
     uses: actions/cache/restore@v6
     with:
       key: ${{steps.cache-params.outputs.key}}
-      restore-keys: ${{runner.os}}-dependencies-${{inputs.nodeVersion}}-
+      restore-keys: ${{github.ref != 'refs/heads/main' && steps.cache-params.outputs.key-prefix || ''}}
       path: ${{steps.cache-params.outputs.paths}}
 
   - name: Install dependencies
