Merge template repository changes: remal-github-actions/template-typescript (#35)

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -48,11 +48,22 @@ jobs:
       env:
         PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
       if: ${{ env.PUSH_BACK_TOKEN && github.event_name == 'push' && startsWith(github.ref, 'refs/heads/') }}
+      uses: remal-github-actions/push-back@v1
+      with:
+        githubToken: ${{ env.PUSH_BACK_TOKEN }}
+        message: Push-back updated files during build
+
+
+    - name: Create tag
+      env:
+        PUSH_BACK_TOKEN: ${{ secrets.PUSH_BACK_TOKEN }}
+      if: ${{ env.PUSH_BACK_TOKEN && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
       run: |
         REMOTE_URL=$(git config --get remote.origin.url)
+        HEAD_COMMIT_SHA=$(git rev-parse HEAD)
         REMOTE_HEAD_COMMIT_SHA=$(git ls-remote "$REMOTE_URL" "${{ github.ref }}" | awk '{ print $1}')
-        if [ "$REMOTE_HEAD_COMMIT_SHA" != "${{ github.sha }}" ]; then
-          echo "::warning::Remote repository branch has been changed, skipping push back"
+        if [ "$REMOTE_HEAD_COMMIT_SHA" != "$HEAD_COMMIT_SHA" ]; then
+          echo "::warning::Remote repository branch has been changed, skipping tag creation"
           exit 0
         fi
 
@@ -61,25 +72,16 @@ jobs:
         git config user.name "${{ github.event.head_commit.committer.name }}"
         git config user.email "${{ github.event.head_commit.committer.email }}"
 
-        echo "::group::Commit updated files during build"
-        git add --all
-        if git commit --quiet --no-status --no-edit -m "[push-back] Commit updated files during build" ; then
-          git push origin "HEAD:${{ github.ref }}"
+        echo "::group::Update tag"
+        FULL_VERSION=$(jq -r '.version' package.json)
+        if [ "$FULL_VERSION" == "null" ]; then
+          echo "::error::Version can't be read from package.json file"
+          exit 1
         fi
+        echo "Version from package.json: $FULL_VERSION"
+
+        MAJOR_VERSION=$(echo "$FULL_VERSION" | cut -f1 -d".")
+        echo "Major version: $MAJOR_VERSION"
+        git tag --force "v$MAJOR_VERSION"
+        git push --force origin "v$MAJOR_VERSION"
         echo "::endgroup::"
-
-        if [ "${{github.ref == 'refs/heads/main'}}" == "true" ]; then
-          echo "::group::Update tag"
-          FULL_VERSION=$(jq -r '.version' package.json)
-          if [ "$FULL_VERSION" == "null" ]; then
-            echo "::error::Version can't be read from package.json file"
-            exit 1
-          fi
-          echo "Version from package.json: $FULL_VERSION"
-
-          MAJOR_VERSION=$(echo "$FULL_VERSION" | cut -f1 -d".")
-          echo "Major version: $MAJOR_VERSION"
-          git tag --force "v$MAJOR_VERSION"
-          git push --force origin "v$MAJOR_VERSION"
-          echo "::endgroup::"
-        fi
