test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -50,7 +50,13 @@ jobs:
       run: |
         echo "::group::Update tag"
         FULL_VERSION=$(jq -r '.version' package.json)
-        echo "FULL_VERSION=$FULL_VERSION"
+        if [ "$FULL_VERSION" == "null" ]; then
+          echo "::error::Version can't be read from package.json file"
+          exit 1
+        fi
+        echo "Version from package.json: $FULL_VERSION"
+        MAJOR_VERSION=$(echo "$FULL_VERSION" | cut -f1 -d".")
+        echo "Major version: $MAJOR_VERSION"
         echo "::endgroup::"
         exit
 
